swagger: "2.0"
info:
  description: "tanyibot api"
  version: 1.0.0
  title: Tanyi Bot open api
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
host: openapi.tanyibot.com
#basePath: /apiOpen/v2
basePath: /v2
tags:
  - name: isv
    description: isv
  - name: tenant
    description: tenant
  - name: phone
    description: phone
schemes:
  - https
paths:
  /payment:
    post:
      tags:
        - payment
      summary: 创建支付对象
      description: 创建支付对象
      operationId: updateIsvInfo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            $ref: "#/definitions/UpdateIsvInfoReq"
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/APIResponse"
